// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymmdcdimdtzqtiaigypy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltbWRjZGltZHR6cXRpYWlneXB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2Mjg1MDgsImV4cCI6MjA2MTIwNDUwOH0.2sk80OSZpCcQWlZuAZMvzuFHl2UovJ3ojQM1DKiwrLs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);